@EmailService_HostAddress = http://localhost:5290

#if (EnableOpenAPI)
GET {{EmailService_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{EmailService_HostAddress}}/weatherforecast/
Accept: application/json

###
