<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EmailService-e7b89247-3ce5-4471-a383-a8266257637b</UserSecretsId>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.0.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.2.26159.112" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Protos\payment.proto">
      <GrpcServices>Server</GrpcServices>
    </None>
  </ItemGroup>
</Project>
